version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: chat-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/chat-app
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - chat-network

  mongodb:
    image: mongo:6.0
    container_name: chat-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=chat-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - chat-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: chat-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - chat-network

volumes:
  mongodb_data:
  rabbitmq_data:

networks:
  chat-network:
    driver: bridge